version: '2.2'

services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: 'pets_home'
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_HOST: 'mysql'

    volumes:
      - data:/volumes/database

    expose:
      - '3306'
  backend:
    container_name: pets_home_backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "${PORT-8080}:${PORT-8080}"

    environment:
      ALLOWED_ORIGINS: https://petshome.cute-lulu.com
      PORT: ${PORT-8080}
      MYSQL_HOST: 'mysql'
      MYSQL_PWD: 'password'
      Redis_Host: 'redis'

    depends_on:
      - mysql
      - redis
  proxy:
    image: nginx:1.17
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  redis:
    container_name: redis
    image: redis:latest

    ports:
      - 6379:6379

  frontend:
    container_name: pets_home_frontend
    image: react
    build: 
      context: ./frontend
    ports:
      - 3000:3000
volumes:
  data:
    external: true