services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: 'pets_home'
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_HOST: 'mysql'

    volumes:
      - data:/volumes/database

    expose:
      - '3306'
  backend:
    container_name: pets_home_backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "${PORT-8080}:${PORT-8080}"

    environment:
      ALLOWED_ORIGINS: ${ALLOWED_ORIGIN:-"http://localhost:3000/"}
      PORT: ${PORT-8080}
      MYSQL_HOST: 'mysql'
      MYSQL_PWD: 'password'
      Redis_Host: 'redis'
      AWS_S3_ACCESS_KEY: ${AWS_S3_ACCESS_KEY}
      AWS_S3_SECRET_KEY: ${AWS_S3_SECRET_KEY}
      BUCKET_NAME: ${AWS_S3_BUCKET_NAME}

    depends_on:
      - mysql
      - redis
  
  proxy:
    image: nginx:1.17
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d
  redis:
    container_name: redis
    image: redis:latest

    ports:
      - 6379:6379

  frontend:
    container_name: pets_home_frontend
    image: react
    build: 
      context: ./frontend
    ports:
      - 3000:3000
    environment:
      REACT_APP_AWS_S3_ACCESS_KEY: ${AWS_S3_ACCESS_KEY}
      REACT_APP_AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      REACT_APP_AWS_S3_SECRET_KEY: ${AWS_S3_BUCKET_NAME}
      REACT_APP_AWS_REGION: ${AWS_ORIGIN}
      REACT_APP_BASE_URL: ${BASE_URL:- "http://localhost:8080/api/v1"}
      REACT_APP_HOME: ${REACT_APP_HOME:-"http://localhost:3000/"}
    
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email petshome876@gmail.com -d petshome.cute-lulu.com --agree-tos
volumes:
    data:
      external: true
